### ISSUE TITLE
Contribution Info

### ISSUE THREAD

**Issue by rodydavis** [kalismeras61/flutter_web_dashboard#1]
<img width="2483" alt="Screen Shot 2019-05-21 at 11 44 49 AM" src="https://user-images.githubusercontent.com/31253215/58110657-f91d6780-7bbd-11e9-8de4-55981de3cd73.png">

Im in the process of porting it to a library that will include bootstrap components for Flutter. 

What can i get as a name and email you want listed as an author on the pubspec.yaml? 
https://github.com/AppleEducate/plugins/tree/master/packages/flutter_bootstrap

**Comment by rodydavis** [comment]
Awesome work on this example!

**Comment by kalismeras61** [comment]
Hi Rody, That's very well, I would very much like to contribute. 

My name is : Yasin ilhan
My e-mail adress is : yasinilhan61@gmail.com

**Comment by sqdsqdqs** [comment]
Hi Rody, That's very well, I would very much like to contribute.

My name is : nizar cht
My e-mail adress is : nizarchtioui42@gmail.com <yasinilhan61@gmail.com>

Le mar. 21 mai 2019 à 16:24, Yasin ilhan <notifications@github.com> a
écrit :

**Comment by rodydavis** [comment]
Thank you!
