### ISSUE TITLE
update i Flutter 1.12 

### ISSUE THREAD

**Issue by hhhxxjj** [kalismeras61/flutter_web_dashboard#3]

**Comment by hhhxxjj** [comment]
As of 1.12, Flutter has early support for running web applications.

I tried to update it, and can't find the following imports:

import 'package:flutter_web_ui/ui.dart' as ui;
import 'package:flutter_web_ui/src/engine.dart' as engine;

**Comment by hhhxxjj** [comment]
Removing web/main.dart directly, the program works.

see: https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK

**Comment by kalismeras61** [comment]
Thanks, i wqaqs not have time for this but today i upgrade it and fix all problems.
